/**
 * WebSocket Connection Status Constants
 */
export const CONNECTION_STATUS = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  CLOSING: 'CLOSING',
  RECONNECTING: 'RECONNECTING',
}
